export var Data = [
  {
    name: "Environment",
    location: "Toronto",
    title: "Grow Trees - On the path to environment sustainability",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Tree Canada",
    subtext: "From 10/01/2019 until 25/02/2019 ",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "grow.png",
    rating: 3,
    hasProgress: false,
    hasSeat: true,
    btntext: "Apply",
    country: "Canada",
  },

  {
    name: "Children",
    location: "Melbourne",
    title: "Education Supplies for Every Pair of Shoes Sold",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Australian Paradise",
    subtext: "From 10/01/2019 until 25/02/2019 ",
    num: 250,
    seat: "Already volunteered",
    date: "09/01/2019",
    time: "Deadline",
    image: "education.png",
    rating: 3,
    hasProgress: false,
    hasSeat: false,
    btntext: "Apply",
    country: "Australia",
  },
  {
    name: "Nutrition",
    location: "Barcelona",
    title: "Nourish the Children in African country",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "The Hunger",
    subtext: "Ongoing Opportunity",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "nourish.png",
    rating: 3,
    hasProgress: false,
    hasSeat: true,
    btntext: "Apply",
    country: "Spain",
  },
  {
    name: "Environment",
    location: "London",
    title: "CSR initiative for Coffee and Farmer Equity",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "CSE Network",
    subtext: "Ongoing Opportunity",
    num: 250,
    seat: "Already volunteered",
    image: "csr.png",
    rating: 3,
    hasProgress: false,
    hasSeat: false,
    btntext: "Apply",
    country: "United Kingdom",
  },
  {
    name: "Animals",
    location: "Cape Town",
    title: "Animal wealfare & save birds campaign",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: " JR Foundation",
    subtext: "Plant 10,000 Trees",
    num: 10,
    seat: "Seats left",
    time: "8000 achieved",
    image: "animal.png",
    rating: 3,
    hasProgress: true,
    progress: 75,
    hasSeat: true,
    btntext: "Apply",
    country: "South Africa",
  },
  {
    name: "Health",
    location: "Paris",
    title: "Plantation and Afforestation programme",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Amaze Doctors",
    subtext: "Plant 10,000 Trees",
    time: "Deadline",
    image: "plantation.png",
    rating: 5,
    hasProgress: true,
    progress: 75,
    btntext: "Apply",
    country: "France",
  },
  {
    name: "Education",
    location: "New York",
    title: "Grow Trees - On the path to environment sustainability",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore officia neque repellendus consectetur hic nulla laboriosam. Doloribus impedit nam excepturi dicta praesentium quaerat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur ",
    subtitle: "Tree Canada",
    image: "grow.png",
    rating: 2,
    hasProgress: false,
    btntext: "View detail",
    country: "United States",
  },

  {
    name: "Children",
    location: "Sydney",
    title: "Education Supplies for Every Pair of Shoes Sold",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Tree Canada",
    subtext: "From 10/01/2019 until 25/02/2019 ",
    num: 250,
    seat: "Already volunteered",
    date: "09/01/2019",
    time: "Deadline",
    image: "education.png",
    rating: 3,
    hasSeat: false,
    btntext: "Apply",
    hasProgress: false,
    country: "Australia",
  },
  {
    name: "Nutrition",
    location: "Berlin",
    title: "Nourish the Children in African country",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Junior Charity",
    subtext: "Ongoing Opportunity",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "nourish.png",
    rating: 4,
    hasSeat: true,
    btntext: "Apply",
    hasProgress: false,
    country: "Germany",
  },
  {
    name: "Nutrition",
    location: "Hamburg",
    title: "Nourish the Children in African country",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Junior Charity",
    subtext: "Ongoing Opportunity",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "nourish.png",
    rating: 4,
    hasSeat: true,
    btntext: "Apply",
    hasProgress: false,
    country: "Germany",
  },
  {
    name: "Nutrition",
    location: "Munich ",
    title: "Nourish the Children in African country",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Junior Charity",
    subtext: "Ongoing Opportunity",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "plantation.png",
    rating: 4,
    hasSeat: true,
    btntext: "Apply",
    hasProgress: false,
    country: "Germany",
  },
  {
    name: "Nutrition",
    location: "Cologne",
    title: "Nourish the Children in African country",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore consequatur dolores odio quisquam",
    subtitle: "Junior Charity",
    subtext: "Ongoing Opportunity",
    num: 10,
    seat: "Seats left",
    date: "09/01/2019",
    time: "Deadline",
    image: "nourish.png",
    rating: 4,
    hasSeat: true,
    btntext: "Apply",
    hasProgress: false,
    country: "Germany",
  },
];
